#!/usr/bin/env ruby

# Kamal secrets management
# This file is used to provide secrets to the deployment

case ARGV[0]
when "REGISTRY_HTTP_SECRET"
  puts ENV.fetch("REGISTRY_HTTP_SECRET")
else
  puts "Unknown secret: #{ARGV[0]}"
  exit 1
end 